//! OpenAPI documentation configuration
//!
//! Central OpenApi struct that collects all paths and schemas for
//! auto-generated API documentation via utoipa + Swagger UI.

use utoipa::openapi::security::{ApiKey, ApiKeyValue, Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OpenYapper Multi-Site CMS API",
        version = "0.1.0",
        description = "A high-performance REST API built with Rust for managing multiple websites with shared content and translations.",
        license(name = "AGPL-3.0-or-later", url = "https://www.gnu.org/licenses/agpl-3.0.html"),
        contact(name = "OpenYapper Team", url = "https://github.com/openyapper/openyapper")
    ),
    servers(
        (url = "/api/v1", description = "API v1")
    ),
    tags(
        (name = "Auth", description = "Authentication and identity"),
        (name = "Clerk Users", description = "Clerk user management"),
        (name = "System", description = "Health and system endpoints"),
        (name = "Sites", description = "Site management"),
        (name = "Blogs", description = "Blog post management"),
        (name = "Pages", description = "Page management"),
        (name = "CV", description = "CV/Resume entries and skills"),
        (name = "Legal", description = "Legal documents and consent management"),
        (name = "Media", description = "Media file management"),
        (name = "Navigation", description = "Navigation structure management"),
        (name = "Social Links", description = "Social media links"),
        (name = "Taxonomy", description = "Tags and categories"),
        (name = "Environments", description = "Environment configuration"),
        (name = "Locales", description = "Locale/language management"),
        (name = "Site Locales", description = "Per-site language/locale management"),
        (name = "Site Members", description = "Site membership management"),
        (name = "Users", description = "User management"),
        (name = "Audit", description = "Audit logs and change history"),
        (name = "Site Settings", description = "Per-site settings management"),
        (name = "Notifications", description = "In-app notification management"),
        (name = "Webhooks", description = "Webhook subscription management"),
        (name = "Redirects", description = "URL redirect management"),
        (name = "Content Templates", description = "Content template management"),
        (name = "API Keys", description = "API key management (requires master key)")
    ),
    paths(
        // System
        crate::handlers::system::index,
        crate::handlers::system::health,
        // Auth
        crate::handlers::auth::get_me,
        crate::handlers::auth::get_profile,
        crate::handlers::auth::export_user_data,
        crate::handlers::auth::delete_account,
        // Sites
        crate::handlers::site::list_sites,
        crate::handlers::site::get_site,
        crate::handlers::site::get_site_by_slug,
        crate::handlers::site::create_site,
        crate::handlers::site::update_site,
        crate::handlers::site::delete_site,
        // Site Settings
        crate::handlers::site_settings::get_site_settings,
        crate::handlers::site_settings::update_site_settings,
        // Blogs
        crate::handlers::blog::list_blogs,
        crate::handlers::blog::list_published_blogs,
        crate::handlers::blog::list_featured_blogs,
        crate::handlers::blog::get_blog,
        crate::handlers::blog::get_blog_by_slug,
        crate::handlers::blog::create_blog,
        crate::handlers::blog::update_blog,
        crate::handlers::blog::delete_blog,
        crate::handlers::blog::get_blog_detail,
        crate::handlers::blog::get_blog_localizations,
        crate::handlers::blog::create_blog_localization,
        crate::handlers::blog::update_blog_localization,
        crate::handlers::blog::delete_blog_localization,
        crate::handlers::blog::clone_blog,
        crate::handlers::blog::review_blog,
        crate::handlers::blog::rss_feed,
        crate::handlers::blog::bulk_blogs,
        // Pages
        crate::handlers::page::list_pages,
        crate::handlers::page::get_page,
        crate::handlers::page::get_page_by_route,
        crate::handlers::page::get_page_sections,
        crate::handlers::page::create_page,
        crate::handlers::page::update_page,
        crate::handlers::page::delete_page,
        crate::handlers::page::create_page_section,
        crate::handlers::page::update_page_section,
        crate::handlers::page::delete_page_section,
        crate::handlers::page::get_section_localizations,
        crate::handlers::page::get_page_section_localizations,
        crate::handlers::page::upsert_section_localization,
        crate::handlers::page::delete_section_localization,
        crate::handlers::page::clone_page,
        crate::handlers::page::review_page,
        crate::handlers::page::bulk_pages,
        // CV
        crate::handlers::cv::list_skills,
        crate::handlers::cv::get_skill,
        crate::handlers::cv::get_skill_by_slug,
        crate::handlers::cv::create_skill,
        crate::handlers::cv::update_skill,
        crate::handlers::cv::delete_skill,
        crate::handlers::cv::list_cv_entries,
        crate::handlers::cv::get_cv_entry,
        crate::handlers::cv::create_cv_entry,
        crate::handlers::cv::update_cv_entry,
        crate::handlers::cv::delete_cv_entry,
        // Legal
        crate::handlers::legal::list_legal_documents,
        crate::handlers::legal::get_legal_document,
        crate::handlers::legal::get_cookie_consent,
        crate::handlers::legal::get_legal_document_by_slug,
        crate::handlers::legal::get_legal_groups,
        crate::handlers::legal::get_legal_items,
        crate::handlers::legal::create_legal_document,
        crate::handlers::legal::update_legal_document,
        crate::handlers::legal::delete_legal_document,
        crate::handlers::legal::create_legal_group,
        crate::handlers::legal::update_legal_group,
        crate::handlers::legal::delete_legal_group,
        crate::handlers::legal::create_legal_item,
        crate::handlers::legal::update_legal_item,
        crate::handlers::legal::delete_legal_item,
        // Media
        crate::handlers::media::list_media,
        crate::handlers::media::get_media,
        crate::handlers::media::create_media,
        crate::handlers::media::upload_media,
        crate::handlers::media::update_media,
        crate::handlers::media::delete_media,
        // Navigation
        crate::handlers::navigation::list_navigation,
        crate::handlers::navigation::list_menu_items,
        crate::handlers::navigation::get_navigation_item,
        crate::handlers::navigation::get_navigation_children,
        crate::handlers::navigation::create_navigation_item,
        crate::handlers::navigation::create_menu_item,
        crate::handlers::navigation::update_navigation_item,
        crate::handlers::navigation::reorder_navigation_items,
        crate::handlers::navigation::reorder_menu_items,
        crate::handlers::navigation::get_navigation_item_localizations,
        crate::handlers::navigation::upsert_navigation_item_localizations,
        crate::handlers::navigation::delete_navigation_item,
        // Navigation Menus
        crate::handlers::navigation_menu::list_navigation_menus,
        crate::handlers::navigation_menu::create_navigation_menu,
        crate::handlers::navigation_menu::get_navigation_menu,
        crate::handlers::navigation_menu::get_navigation_menu_by_slug,
        crate::handlers::navigation_menu::update_navigation_menu,
        crate::handlers::navigation_menu::delete_navigation_menu,
        crate::handlers::navigation_menu::get_navigation_tree,
        // Social Links
        crate::handlers::social::list_social_links,
        crate::handlers::social::get_social_link,
        crate::handlers::social::create_social_link,
        crate::handlers::social::update_social_link,
        crate::handlers::social::reorder_social_links,
        crate::handlers::social::delete_social_link,
        // Taxonomy
        crate::handlers::taxonomy::list_tags,
        crate::handlers::taxonomy::get_tag,
        crate::handlers::taxonomy::get_tag_by_slug,
        crate::handlers::taxonomy::get_content_tags,
        crate::handlers::taxonomy::list_categories,
        crate::handlers::taxonomy::get_category,
        crate::handlers::taxonomy::get_category_children,
        crate::handlers::taxonomy::get_content_categories,
        crate::handlers::taxonomy::create_tag,
        crate::handlers::taxonomy::update_tag,
        crate::handlers::taxonomy::delete_tag,
        crate::handlers::taxonomy::create_category,
        crate::handlers::taxonomy::update_category,
        crate::handlers::taxonomy::delete_category,
        crate::handlers::taxonomy::assign_category_to_content,
        crate::handlers::taxonomy::remove_category_from_content,
        crate::handlers::taxonomy::get_categories_with_blog_counts,
        // Environments
        crate::handlers::environment::list_environments,
        crate::handlers::environment::get_environment,
        crate::handlers::environment::get_default_environment,
        // Locales
        crate::handlers::locale::list_locales,
        crate::handlers::locale::get_locale,
        crate::handlers::locale::get_locale_by_code,
        crate::handlers::locale::create_locale,
        crate::handlers::locale::update_locale,
        crate::handlers::locale::delete_locale,
        // Audit
        crate::handlers::audit::list_audit_logs,
        crate::handlers::audit::get_entity_audit_logs,
        crate::handlers::audit::get_entity_history,
        crate::handlers::audit::revert_changes,
        // API Keys
        crate::handlers::api_key::create_api_key,
        crate::handlers::api_key::list_api_keys,
        crate::handlers::api_key::get_api_key,
        crate::handlers::api_key::update_api_key,
        crate::handlers::api_key::delete_api_key,
        crate::handlers::api_key::block_api_key,
        crate::handlers::api_key::unblock_api_key,
        crate::handlers::api_key::revoke_api_key,
        crate::handlers::api_key::get_api_key_usage,
        // Site Locales
        crate::handlers::site_locale::list_site_locales,
        crate::handlers::site_locale::add_site_locale,
        crate::handlers::site_locale::update_site_locale,
        crate::handlers::site_locale::remove_site_locale,
        crate::handlers::site_locale::set_site_default_locale,
        // Site Members
        crate::handlers::site_membership::list_site_members,
        crate::handlers::site_membership::add_site_member,
        crate::handlers::site_membership::update_member_role,
        crate::handlers::site_membership::remove_site_member,
        crate::handlers::site_membership::transfer_ownership,
        crate::handlers::site_membership::get_my_memberships,
        // Clerk Users
        crate::handlers::clerk_user::list_clerk_users,
        crate::handlers::clerk_user::get_clerk_user,
        crate::handlers::clerk_user::update_clerk_user_role,
        // Notifications
        crate::handlers::notification::list_notifications,
        crate::handlers::notification::get_unread_count,
        crate::handlers::notification::mark_notification_read,
        crate::handlers::notification::mark_all_notifications_read,
        // Webhooks
        crate::handlers::webhook::list_webhooks,
        crate::handlers::webhook::get_webhook,
        crate::handlers::webhook::create_webhook,
        crate::handlers::webhook::update_webhook,
        crate::handlers::webhook::delete_webhook,
        crate::handlers::webhook::test_webhook,
        crate::handlers::webhook::list_webhook_deliveries,
        // Redirects
        crate::handlers::redirect::list_redirects,
        crate::handlers::redirect::get_redirect,
        crate::handlers::redirect::create_redirect,
        crate::handlers::redirect::update_redirect,
        crate::handlers::redirect::delete_redirect,
        crate::handlers::redirect::lookup_redirect,
        // Content Templates
        crate::handlers::content_template::list_content_templates,
        crate::handlers::content_template::get_content_template,
        crate::handlers::content_template::create_content_template,
        crate::handlers::content_template::update_content_template,
        crate::handlers::content_template::delete_content_template,
        // Config
        crate::handlers::config::get_config,
    ),
    components(schemas(
        // Auth
        crate::dto::auth::AuthInfoResponse,
        crate::dto::auth::ProfileResponse,
        crate::dto::auth::ExportApiKeyRecord,
        crate::dto::auth::UserDataExportResponse,
        // Error types
        crate::errors::ProblemDetails,
        crate::errors::FieldError,
        // Health
        crate::dto::health::HealthResponse,
        crate::dto::health::ServiceHealth,
        crate::dto::health::StorageHealth,
        // Pagination
        crate::utils::pagination::PaginationMeta,
        crate::dto::blog::PaginatedBlogs,
        crate::dto::page::PaginatedPages,
        crate::dto::media::PaginatedMedia,
        crate::dto::audit::PaginatedAuditLogs,
        crate::dto::api_key::PaginatedApiKeys,
        crate::dto::document::PaginatedDocuments,
        crate::dto::cv::PaginatedCvEntries,
        crate::dto::cv::PaginatedSkills,
        crate::dto::legal::PaginatedLegalDocuments,
        crate::dto::taxonomy::PaginatedTags,
        crate::dto::taxonomy::PaginatedCategories,
        // Model enums
        crate::models::content::ContentStatus,
        crate::models::content::TranslationStatus,
        crate::models::api_key::ApiKeyPermission,
        crate::models::api_key::ApiKeyStatus,
        crate::models::cv::CvEntryType,
        crate::models::cv::SkillCategory,
        crate::models::media::StorageProvider,
        crate::models::media::MediaVariantType,
        crate::models::page::PageType,
        crate::models::page::SectionType,
        crate::models::legal::LegalDocType,
        crate::models::environment::EnvironmentType,
        crate::models::locale::TextDirection,
        crate::models::audit::AuditAction,
        // Site DTOs
        crate::dto::site::CreateSiteRequest,
        crate::dto::site::UpdateSiteRequest,
        crate::dto::site::SiteResponse,
        // Site Settings DTOs
        crate::dto::site_settings::SiteSettingsResponse,
        crate::dto::site_settings::UpdateSiteSettingsRequest,
        crate::dto::site_settings::PreviewTemplate,
        // Bulk DTOs
        crate::dto::bulk::BulkAction,
        crate::dto::bulk::BulkContentRequest,
        crate::dto::bulk::BulkItemResult,
        crate::dto::bulk::BulkContentResponse,
        // Blog DTOs
        crate::dto::blog::CreateBlogRequest,
        crate::dto::blog::UpdateBlogRequest,
        crate::dto::blog::BlogListItem,
        crate::dto::blog::BlogResponse,
        crate::dto::blog::BlogDetailResponse,
        // Content DTOs
        crate::dto::content::CreateLocalizationRequest,
        crate::dto::content::UpdateLocalizationRequest,
        crate::dto::content::LocalizationResponse,
        // Page DTOs
        crate::dto::page::CreatePageRequest,
        crate::dto::page::UpdatePageRequest,
        crate::dto::page::CreatePageSectionRequest,
        crate::dto::page::UpdatePageSectionRequest,
        crate::dto::page::PageListItem,
        crate::dto::page::PageResponse,
        crate::dto::page::PageSectionResponse,
        crate::dto::page::SectionLocalizationResponse,
        crate::dto::page::UpsertSectionLocalizationRequest,
        // CV DTOs
        crate::dto::cv::CreateSkillRequest,
        crate::dto::cv::UpdateSkillRequest,
        crate::dto::cv::SkillResponse,
        crate::dto::cv::CreateCvEntryRequest,
        crate::dto::cv::UpdateCvEntryRequest,
        crate::dto::cv::CvEntryResponse,
        // Legal DTOs
        crate::dto::legal::CreateLegalDocumentRequest,
        crate::dto::legal::UpdateLegalDocumentRequest,
        crate::dto::legal::CreateLegalGroupRequest,
        crate::dto::legal::UpdateLegalGroupRequest,
        crate::dto::legal::CreateLegalItemRequest,
        crate::dto::legal::UpdateLegalItemRequest,
        crate::dto::legal::LegalDocumentResponse,
        crate::dto::legal::LegalGroupResponse,
        crate::dto::legal::LegalItemResponse,
        crate::dto::legal::LegalDocumentWithGroups,
        crate::dto::legal::LegalGroupWithItems,
        crate::dto::legal::LegalDocumentDetailResponse,
        crate::dto::legal::LegalDocLocalizationResponse,
        // Media DTOs
        crate::dto::media::UploadMediaRequest,
        crate::dto::media::UpdateMediaRequest,
        crate::dto::media::AddMediaMetadataRequest,
        crate::dto::media::MediaListItem,
        crate::dto::media::MediaVariantResponse,
        crate::dto::media::MediaResponse,
        // Navigation DTOs
        crate::dto::navigation::CreateNavigationItemRequest,
        crate::dto::navigation::UpdateNavigationItemRequest,
        crate::dto::navigation::NavigationItemResponse,
        crate::dto::navigation::NavigationTree,
        crate::dto::navigation::ReorderNavigationItem,
        crate::dto::navigation::ReorderNavigationItemsRequest,
        crate::dto::navigation::ReorderNavigationTreeItem,
        crate::dto::navigation::ReorderNavigationTreeRequest,
        crate::dto::navigation::NavigationItemLocalizationInput,
        crate::dto::navigation::NavigationItemLocalizationResponse,
        // Navigation Menu DTOs
        crate::dto::navigation_menu::CreateNavigationMenuRequest,
        crate::dto::navigation_menu::UpdateNavigationMenuRequest,
        crate::dto::navigation_menu::NavigationMenuResponse,
        crate::dto::navigation_menu::MenuLocalizationInput,
        crate::dto::navigation_menu::MenuLocalizationResponse,
        // Social DTOs
        crate::dto::social::CreateSocialLinkRequest,
        crate::dto::social::UpdateSocialLinkRequest,
        crate::dto::social::SocialLinkResponse,
        crate::dto::social::ReorderItem,
        crate::dto::social::ReorderSocialLinksRequest,
        // Taxonomy DTOs
        crate::dto::taxonomy::CreateTagRequest,
        crate::dto::taxonomy::UpdateTagRequest,
        crate::dto::taxonomy::CreateCategoryRequest,
        crate::dto::taxonomy::UpdateCategoryRequest,
        crate::dto::taxonomy::TagResponse,
        crate::dto::taxonomy::CategoryResponse,
        crate::dto::taxonomy::CategoryTree,
        crate::dto::taxonomy::AssignCategoryRequest,
        crate::dto::taxonomy::CategoryWithCountResponse,
        // Environment DTOs
        crate::dto::environment::CreateEnvironmentRequest,
        crate::dto::environment::UpdateEnvironmentRequest,
        crate::dto::environment::EnvironmentResponse,
        // Locale DTOs
        crate::dto::locale::CreateLocaleRequest,
        crate::dto::locale::UpdateLocaleRequest,
        crate::dto::locale::LocaleResponse,
        // Audit DTOs
        crate::dto::audit::AuditLogResponse,
        crate::dto::audit::ChangeHistoryResponse,
        crate::dto::audit::RevertChangesRequest,
        crate::dto::audit::RevertChangesResponse,
        // API Key DTOs
        crate::dto::api_key::CreateApiKeyRequest,
        crate::dto::api_key::UpdateApiKeyRequest,
        crate::dto::api_key::BlockApiKeyRequest,
        crate::dto::api_key::CreateApiKeyResponse,
        crate::dto::api_key::ApiKeyResponse,
        crate::dto::api_key::ApiKeyListItem,
        crate::dto::api_key::ApiKeyUsageResponse,
        // Site Locale DTOs
        crate::dto::site_locale::AddSiteLocaleRequest,
        crate::dto::site_locale::UpdateSiteLocaleRequest,
        crate::dto::site_locale::SiteLocaleResponse,
        crate::dto::site_locale::SiteLocaleInput,
        // Site Membership DTOs
        crate::dto::site_membership::SiteMembershipResponse,
        crate::dto::site_membership::AddSiteMemberRequest,
        crate::dto::site_membership::UpdateMemberRoleRequest,
        crate::dto::site_membership::TransferOwnershipRequest,
        crate::dto::site_membership::MembershipSummary,
        crate::models::site_membership::SiteRole,
        // Clerk DTOs
        crate::dto::clerk::ClerkUserResponse,
        crate::dto::clerk::ClerkUserListResponse,
        crate::dto::clerk::UpdateClerkUserRoleRequest,
        // Webhook DTOs
        crate::dto::webhook::CreateWebhookRequest,
        crate::dto::webhook::UpdateWebhookRequest,
        crate::dto::webhook::WebhookResponse,
        crate::dto::webhook::WebhookDeliveryResponse,
        crate::dto::webhook::PaginatedWebhooks,
        crate::dto::webhook::PaginatedWebhookDeliveries,
        // Redirect DTOs
        crate::dto::redirect::CreateRedirectRequest,
        crate::dto::redirect::UpdateRedirectRequest,
        crate::dto::redirect::RedirectResponse,
        crate::dto::redirect::RedirectLookupResponse,
        crate::dto::redirect::PaginatedRedirects,
        // Content Template DTOs
        crate::dto::content_template::CreateContentTemplateRequest,
        crate::dto::content_template::UpdateContentTemplateRequest,
        crate::dto::content_template::ContentTemplateResponse,
        crate::dto::content_template::PaginatedContentTemplates,
        // Notification DTOs
        crate::dto::notification::NotificationResponse,
        crate::dto::notification::UnreadCountResponse,
        crate::dto::notification::MarkAllReadResponse,
        crate::dto::notification::PaginatedNotifications,
        // Review DTOs
        crate::dto::review::ReviewAction,
        crate::dto::review::ReviewActionRequest,
        crate::dto::review::ReviewActionResponse,
        // Config DTOs
        crate::dto::config::ConfigResponse,
    )),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

/// Adds X-API-Key and Bearer auth security schemes to the OpenAPI spec
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "api_key",
                SecurityScheme::ApiKey(ApiKey::Header(ApiKeyValue::new("X-API-Key"))),
            );
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
