import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/prerequisites',
        'getting-started/installation',
        'getting-started/first-run',
        'getting-started/new-user-guide',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/backend',
        'architecture/admin',
        'architecture/database',
        'architecture/authentication',
        'architecture/storage',
        'architecture/rate-limiting',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/authentication',
        'api/error-handling',
        'api/pagination',
        {
          type: 'category',
          label: 'Endpoints',
          items: [
            'api/endpoints/sites',
            'api/endpoints/blogs',
            'api/endpoints/pages',
            'api/endpoints/documents',
            'api/endpoints/cv-entries',
            'api/endpoints/legal',
            'api/endpoints/media',
            'api/endpoints/navigation',
            'api/endpoints/taxonomy',
            'api/endpoints/social-links',
            'api/endpoints/webhooks',
            'api/endpoints/redirects',
            'api/endpoints/content-templates',
            'api/endpoints/api-keys',
            'api/endpoints/users',
            'api/endpoints/audit',
            'api/endpoints/notifications',
            'api/endpoints/system',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Admin Guide',
      items: [
        'admin-guide/overview',
        'admin-guide/authentication',
        'admin-guide/dashboard',
        'admin-guide/sites',
        {
          type: 'category',
          label: 'Content',
          items: [
            'admin-guide/content/blogs',
            'admin-guide/content/pages',
            'admin-guide/content/documents',
            'admin-guide/content/cv',
            'admin-guide/content/legal',
          ],
        },
        'admin-guide/media',
        'admin-guide/navigation',
        'admin-guide/taxonomy',
        'admin-guide/social-links',
        'admin-guide/webhooks',
        'admin-guide/redirects',
        'admin-guide/api-keys',
        'admin-guide/members',
        'admin-guide/audit-log',
        'admin-guide/notifications',
        'admin-guide/settings',
        'admin-guide/locales',
        'admin-guide/command-palette',
        'admin-guide/content-templates',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/docker',
        'deployment/railway',
        'deployment/environment-variables',
        'deployment/tls',
        'deployment/s3-storage',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer/project-structure',
        'developer/backend-guide',
        'developer/admin-guide',
        'developer/testing',
        'developer/database-migrations',
        'developer/coding-standards',
        'developer/ci-cd',
        'developer/contributing',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      items: [
        'templates/overview',
        'templates/astro-blog',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
